# Site settings
baseurl: "/courses/clio3.2014"
url: "http://lincolnmullen.com/courses/clio3.2014"
source: source
destination: public

# Build settings
markdown: kramdown
permalink: pretty
lsi: false

# Draft or not?
draft: false

# Course information
title: "Clio 3: Programming in History/New Media"
course_catalog: http://historyarthistory.gmu.edu/courses/2544/course_sections/16549
course_credithours: 3
course_hashtag: clio3
course_meetingtime: "Wed., 7:20&ndash;10:00 p.m."
course_number: "HIST 698"
course_prerequisites: "HIST 696, 697 strongly suggested"
course_room: "Research Hall 402"
course_semester: "Fall 2014"
instructor_email: lmullen@gmu.edu
instructor_name: Lincoln Mullen
instructor_office: "Research Hall 457"
instructor_officehours: TBD
instructor_twitter: lincolnmullen
instructor_website: http://lincolnmullen.com
course_description: "An introduction to programming for historians."
